/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RRoomIdImport } from './routes/r/$roomId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RRoomIdRoute = RRoomIdImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$roomId': typeof RRoomIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$roomId': typeof RRoomIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/r/$roomId': typeof RRoomIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$roomId'
  id: '__root__' | '/' | '/r/$roomId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RRoomIdRoute: typeof RRoomIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RRoomIdRoute: RRoomIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/r/$roomId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/r/$roomId": {
      "filePath": "r/$roomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
