services:
  meet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SENTRY_ORG: ${SENTRY_ORG:-}
        SENTRY_PROJECT: ${SENTRY_PROJECT:-}
      secrets:
        - sentry_auth_token
    image: meet
    container_name: meet
    environment:
      NODE_ENV: production
      PORT: "3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - bond

secrets:
  sentry_auth_token:
    environment: SENTRY_AUTH_TOKEN

networks:
  bond:
    external: true
