networks:
  bond:
    external: true

services:
  server:
    image: caddy
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - bond
