-- +goose Up
CREATE TABLE "room" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"public_id" text NOT NULL UNIQUE,
	"created_by" integer REFERENCES "user" ("id") ON DELETE SET NULL,
	"created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "room_created_by_idx" ON "room" ("created_by");
CREATE INDEX "room_public_id_idx" ON "room" ("public_id");

-- +goose Down
DROP TABLE "room";
