-- +goose Up
CREATE TABLE "room_event" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"event" varchar(255),
	"room_id" varchar(255),
	"data" jsonb
);

-- +goose Down
DROP TABLE "room_event";
