-- +goose Up
CREATE TABLE "user" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"email_verified" boolean NOT NULL DEFAULT false,
	"image" text,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "session" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id" integer NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
	"token" text NOT NULL UNIQUE,
	"expires_at" timestamptz NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "session_user_id_idx" ON "session" ("user_id");

CREATE TABLE "account" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id" integer NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamptz,
	"refresh_token_expires_at" timestamptz,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "account_user_id_idx" ON "account" ("user_id");

CREATE TABLE "verification" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamptz NOT NULL,
	"created_at" timestamptz NOT NULL DEFAULT now(),
	"updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");

-- +goose Down
DROP TABLE "verification";
DROP TABLE "account";
DROP TABLE "session";
DROP TABLE "user";
