bind 127.0.0.1 ::1
protected-mode yes
port 6380
timeout 0
tcp-keepalive 300
# Disable the default user (or password-protect it)
user default off

# Create user "atlantic" with full access
user atlantic on >Oj3ybV2kZ2o5nO ~* &* +@all
