/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ApiSentryRouteImport } from './routes/api/sentry'
import { Route as PrivateRoomRoomIdRouteImport } from './routes/_private/room/$roomId'
import { Route as PrivateTestIndexRouteImport } from './routes/_private/test/index'
import { Route as PublicEgressIndexRouteImport } from './routes/_public/egress/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksLivekitRouteImport } from './routes/api/webhooks/livekit'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSentryRoute = ApiSentryRouteImport.update({
  id: '/api/sentry',
  path: '/api/sentry',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoomRoomIdRoute = PrivateRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateTestIndexRoute = PrivateTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicEgressIndexRoute = PublicEgressIndexRouteImport.update({
  id: '/egress/',
  path: '/egress/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLivekitRoute = ApiWebhooksLivekitRouteImport.update({
  id: '/api/webhooks/livekit',
  path: '/api/webhooks/livekit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/login': typeof PublicLoginRoute
  '/api/sentry': typeof ApiSentryRoute
  '/room/$roomId': typeof PrivateRoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
  '/test/': typeof PrivateTestIndexRoute
  '/egress/': typeof PublicEgressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/login': typeof PublicLoginRoute
  '/api/sentry': typeof ApiSentryRoute
  '/room/$roomId': typeof PrivateRoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
  '/test': typeof PrivateTestIndexRoute
  '/egress': typeof PublicEgressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/api/sentry': typeof ApiSentryRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/room/$roomId': typeof PrivateRoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
  '/_private/test/': typeof PrivateTestIndexRoute
  '/_public/egress/': typeof PublicEgressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/sentry'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/api/webhooks/livekit'
    | '/test/'
    | '/egress/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/sentry'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/api/webhooks/livekit'
    | '/test'
    | '/egress'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_public/login'
    | '/api/sentry'
    | '/_private/'
    | '/_private/room/$roomId'
    | '/api/auth/$'
    | '/api/webhooks/livekit'
    | '/_private/test/'
    | '/_public/egress/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiSentryRoute: typeof ApiSentryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksLivekitRoute: typeof ApiWebhooksLivekitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/sentry': {
      id: '/api/sentry'
      path: '/api/sentry'
      fullPath: '/api/sentry'
      preLoaderRoute: typeof ApiSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/room/$roomId': {
      id: '/_private/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof PrivateRoomRoomIdRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/test/': {
      id: '/_private/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof PrivateTestIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/egress/': {
      id: '/_public/egress/'
      path: '/egress'
      fullPath: '/egress/'
      preLoaderRoute: typeof PublicEgressIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/livekit': {
      id: '/api/webhooks/livekit'
      path: '/api/webhooks/livekit'
      fullPath: '/api/webhooks/livekit'
      preLoaderRoute: typeof ApiWebhooksLivekitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateRoomRoomIdRoute: typeof PrivateRoomRoomIdRoute
  PrivateTestIndexRoute: typeof PrivateTestIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateRoomRoomIdRoute: PrivateRoomRoomIdRoute,
  PrivateTestIndexRoute: PrivateTestIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicEgressIndexRoute: typeof PublicEgressIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicEgressIndexRoute: PublicEgressIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiSentryRoute: ApiSentryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksLivekitRoute: ApiWebhooksLivekitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
