/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSentryRouteImport } from './routes/api/sentry'
import { Route as EgressIndexRouteImport } from './routes/egress/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ApiWebhooksLivekitRouteImport } from './routes/api/webhooks/livekit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryRoute = ApiSentryRouteImport.update({
  id: '/api/sentry',
  path: '/api/sentry',
  getParentRoute: () => rootRouteImport,
} as any)
const EgressIndexRoute = EgressIndexRouteImport.update({
  id: '/egress/',
  path: '/egress/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLivekitRoute = ApiWebhooksLivekitRouteImport.update({
  id: '/api/webhooks/livekit',
  path: '/api/webhooks/livekit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sentry': typeof ApiSentryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/egress/': typeof EgressIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sentry': typeof ApiSentryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/egress': typeof EgressIndexRoute
  '/test': typeof TestIndexRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sentry': typeof ApiSentryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/egress/': typeof EgressIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/sentry'
    | '/room/$roomId'
    | '/egress/'
    | '/test/'
    | '/api/webhooks/livekit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/sentry'
    | '/room/$roomId'
    | '/egress'
    | '/test'
    | '/api/webhooks/livekit'
  id:
    | '__root__'
    | '/'
    | '/api/sentry'
    | '/room/$roomId'
    | '/egress/'
    | '/test/'
    | '/api/webhooks/livekit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSentryRoute: typeof ApiSentryRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  EgressIndexRoute: typeof EgressIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  ApiWebhooksLivekitRoute: typeof ApiWebhooksLivekitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry': {
      id: '/api/sentry'
      path: '/api/sentry'
      fullPath: '/api/sentry'
      preLoaderRoute: typeof ApiSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egress/': {
      id: '/egress/'
      path: '/egress'
      fullPath: '/egress/'
      preLoaderRoute: typeof EgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/livekit': {
      id: '/api/webhooks/livekit'
      path: '/api/webhooks/livekit'
      fullPath: '/api/webhooks/livekit'
      preLoaderRoute: typeof ApiWebhooksLivekitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSentryRoute: ApiSentryRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  EgressIndexRoute: EgressIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ApiWebhooksLivekitRoute: ApiWebhooksLivekitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
